name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * * # daily at 00:00

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GRPC_WEB_VERSION: 1.2.1

    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: Install grpc-web
      shell: bash
      run: |
        wget https://github.com/grpc/grpc-web/releases/download/${{env.GRPC_WEB_VERSION}}/protoc-gen-grpc-web-${{env.GRPC_WEB_VERSION}}-linux-x86_64
        sudo mv protoc-gen-grpc-web-${{env.GRPC_WEB_VERSION}}-linux-x86_64 /usr/local/bin/protoc-gen-grpc-web
        sudo chmod +x /usr/local/bin/protoc-gen-grpc-web

    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Cache node modules
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: node_modules
        key: ${{ hashFiles('yarn.lock') }}

    - name: yarn install
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: |
        yarn install

    - name: grpc proto
      run: yarn proto

    - name: eslint
      run: yarn lint

    - name: Build
      run: yarn build

    - name: Unit Test
      run: yarn test:unit

    # - name: E2E Test
    #   run: yarn test:e2e